spring:
  application:
    name: hospitalflow-erp

  datasource:
    url: jdbc:postgresql://localhost:5432/hospitalflow_erp_db
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8081